export type Division =
  | 'Badan Pengurus Harian'
  | 'Divisi Acara'
  | 'Divisi Pendataan'
  | 'Divisi Media'
  | 'Divisi Humas'
  | 'Divisi Logistik';

export const DIVISIONS: Division[] = [
  'Badan Pengurus Harian',
  'Divisi Acara',
  'Divisi Pendataan',
  'Divisi Media',
  'Divisi Humas',
  'Divisi Logistik',
];

export const ALL_DIVISIONS = 'Semua Divisi' as const;
export type DivisionFilter = Division | typeof ALL_DIVISIONS;

export type Currency = 'EGP' | 'IDR';

export const ALL_CURRENCIES = 'Semua Mata Uang' as const;
export type CurrencyFilter = Currency | typeof ALL_CURRENCIES;

export type TransactionType = 'income' | 'expense';

export const ALL_TYPES = 'Semua Tipe' as const;
export type TypeFilter = TransactionType | typeof ALL_TYPES;

export const TYPE_LABEL: Record<TransactionType, string> = {
  income: 'Pemasukan',
  expense: 'Pengeluaran',
};

export const CURRENCY_LABEL: Record<Currency, string> = {
  EGP: 'EGP',
  IDR: 'IDR',
};

/**
 * Shape of a row returned from public.cashbook_entries.
 */
export interface CashbookEntry {
  id: string;
  transaction_date: string;
  type: TransactionType;
  category: string;
  description: string | null;
  division: Division | null;
  amount: number;
  currency: Currency;
  payment_method: string;
  pic: string | null;
  attachment_url: string | null;
  created_by: string;
  updated_by: string | null;
  created_at: string;
  updated_at: string;
}

/**
 * Data required when creating a new cashbook entry.
 *
 * category and payment_method are required by the existing database
 * schema, but they are not user-facing form fields.
 * They are derived internally in the mutation layer.
 */
export interface CreateCashbookEntryInput {
  transaction_date: string;
  type: TransactionType;
  category: string;
  description: string;
  division: Division;
  amount: number;
  currency: Currency;
  payment_method: string;
  attachment_url: string | null;
}

/**
 * Partial input for future update operations.
 *
 * Update is not currently required by the main UI, but keeping
 * the shape here makes the table contract complete.
 */
export interface UpdateCashbookEntryInput {
  transaction_date?: string;
  type?: TransactionType;
  category?: string;
  description?: string | null;
  division?: Division;
  amount?: number;
  currency?: Currency;
  payment_method?: string;
  pic?: string | null;
  attachment_url?: string | null;
}

/**
 * Table-shape override for feature-local Supabase typing,
 * following the same pattern used by the RAB feature.
 */
export interface CashbookTable {
  Row: CashbookEntry;
  Insert: CreateCashbookEntryInput;
  Update: UpdateCashbookEntryInput;
  Relationships: [];
}

/**
 * A cashbook row after running-balance calculation.
 *
 * `displayIndex` is generated by the UI and is not stored in DB.
 * `runningEgp` and `runningIdr` are derived values.
 */
export interface CashbookDisplayRow extends CashbookEntry {
  displayIndex: number;
  runningEgp: number;
  runningIdr: number;
}

/**
 * Summary derived from the complete cashbook history.
 */
export interface CashbookSummary {
  totalIncomeEgp: number;
  totalExpenseEgp: number;
  balanceEgp: number;

  totalIncomeIdr: number;
  totalExpenseIdr: number;
  balanceIdr: number;
}

/**
 * Result of the full filtering/sorting pipeline.
 */
export interface CashbookViewData {
  entries: CashbookDisplayRow[];
  totalEntries: number;
}

/**
 * Display sorting options.
 *
 * Running balance is NOT recalculated according to this sorting.
 * It always follows chronological transaction order.
 */
export type SortOption =
  | 'newest'
  | 'oldest'
  | 'largest_egp'
  | 'smallest_egp'
  | 'largest_idr'
  | 'smallest_idr';

export const SORT_LABELS: Record<SortOption, string> = {
  newest: 'Terbaru',
  oldest: 'Terlama',
  largest_egp: 'Nominal Terbesar — EGP',
  smallest_egp: 'Nominal Terkecil — EGP',
  largest_idr: 'Nominal Terbesar — IDR',
  smallest_idr: 'Nominal Terkecil — IDR',
};

/**
 * Current filter state used by the Cashbook UI.
 */
export interface CashbookFilters {
  division: DivisionFilter;
  type: TypeFilter;
  currency: CurrencyFilter;
  sort: SortOption;
}

/**
 * Initial/default filter state.
 */
export const DEFAULT_CASHBOOK_FILTERS: CashbookFilters = {
  division: ALL_DIVISIONS,
  type: ALL_TYPES,
  currency: ALL_CURRENCIES,
  sort: 'newest',
};

/**
 * Export columns available in the XLSX export modal.
 *
 * These are presentation/export fields, not necessarily database
 * columns.
 */
export const EXPORT_COLUMNS = [
  'transaction_date',
  'type',
  'description',
  'division',
  'attachment_url',
  'amount_egp',
  'amount_idr',
  'running_egp',
  'running_idr',
] as const;

export type ExportColumn = (typeof EXPORT_COLUMNS)[number];

export const EXPORT_COLUMN_LABELS: Record<ExportColumn, string> = {
  transaction_date: 'Tanggal',
  type: 'Tipe Transaksi',
  description: 'Keterangan',
  division: 'Divisi',
  attachment_url: 'Bukti Nota',
  amount_egp: 'Nominal EGP',
  amount_idr: 'Nominal IDR',
  running_egp: 'Saldo EGP',
  running_idr: 'Saldo IDR',
};

/**
 * Export row generated from the already filtered/sorted display data.
 */
export interface CashbookExportRow {
  transaction_date?: string;
  type?: string;
  description?: string;
  division?: string;
  attachment_url?: string;
  amount_egp?: number | string;
  amount_idr?: number | string;
  running_egp?: number | string;
  running_idr?: number | string;
}

/**
 * Parameters used by filtering/sorting utilities.
 */
export interface CashbookQueryOptions {
  entries: CashbookEntry[];
  filters: CashbookFilters;
}

/**
 * Result returned by the running-balance calculator.
 */
export interface RunningBalanceResult {
  rows: CashbookDisplayRow[];
  finalEgp: number;
  finalIdr: number;
}

/**
 * Validation state for the form.
 */
export interface CashbookFormErrors {
  transaction_date?: string;
  type?: string;
  description?: string;
  division?: string;
  currency?: string;
  amount?: string;
  attachment_url?: string;
}

/**
 * Optional form state type.
 */
export interface CashbookFormValues {
  transaction_date: string;
  type: TransactionType;
  description: string;
  division: Division | '';
  currency: Currency | '';
  amount: string;
  attachment_url: string;
}