/**
 * Single source of truth for country list — ISO 3166-1 alpha-2 code
 * paired with the Arabic display name. Used consistently everywhere
 * this feature deals with countries: form dropdown, database
 * (stores only the code — see migration comment on
 * graduates.country_code), filter, search, sort, summary, export,
 * preview. Never duplicate this list in another component.
 *
 * Two names are pinned exactly per business rule (section 7):
 * - CG (Congo, Republic of the) -> "كونغو" (short form only, never
 *   the long "جمهورية الكونغو" form)
 * - KG (Kyrgyzstan)             -> "قرغستان" (this exact spelling,
 *   never "قرغيستان")
 *
 * CD (Democratic Republic of the Congo) is kept as a separate,
 * distinctly-named entry so it is never confused with CG above.
 */
export interface Country {
  code: string;
  nameAr: string;
}

export const COUNTRIES: Country[] = [
  { code: 'EG', nameAr: 'مصر' },
  { code: 'SA', nameAr: 'السعودية' },
  { code: 'AE', nameAr: 'الإمارات' },
  { code: 'KW', nameAr: 'الكويت' },
  { code: 'QA', nameAr: 'قطر' },
  { code: 'BH', nameAr: 'البحرين' },
  { code: 'OM', nameAr: 'عمان' },
  { code: 'YE', nameAr: 'اليمن' },
  { code: 'JO', nameAr: 'الأردن' },
  { code: 'LB', nameAr: 'لبنان' },
  { code: 'SY', nameAr: 'سوريا' },
  { code: 'IQ', nameAr: 'العراق' },
  { code: 'PS', nameAr: 'فلسطين' },
  { code: 'LY', nameAr: 'ليبيا' },
  { code: 'TN', nameAr: 'تونس' },
  { code: 'DZ', nameAr: 'الجزائر' },
  { code: 'MA', nameAr: 'المغرب' },
  { code: 'MR', nameAr: 'موريتانيا' },
  { code: 'SD', nameAr: 'السودان' },
  { code: 'SO', nameAr: 'الصومال' },
  { code: 'DJ', nameAr: 'جيبوتي' },
  { code: 'KM', nameAr: 'جزر القمر' },
  { code: 'ID', nameAr: 'إندونيسيا' },
  { code: 'MY', nameAr: 'ماليزيا' },
  { code: 'BN', nameAr: 'بروناي' },
  { code: 'SG', nameAr: 'سنغافورة' },
  { code: 'TH', nameAr: 'تايلاند' },
  { code: 'PH', nameAr: 'الفلبين' },
  { code: 'VN', nameAr: 'فيتنام' },
  { code: 'KH', nameAr: 'كمبوديا' },
  { code: 'LA', nameAr: 'لاوس' },
  { code: 'MM', nameAr: 'ميانمار' },
  { code: 'TL', nameAr: 'تيمور الشرقية' },
  { code: 'CN', nameAr: 'الصين' },
  { code: 'JP', nameAr: 'اليابان' },
  { code: 'KR', nameAr: 'كوريا الجنوبية' },
  { code: 'KP', nameAr: 'كوريا الشمالية' },
  { code: 'MN', nameAr: 'منغوليا' },
  { code: 'TW', nameAr: 'تايوان' },
  { code: 'HK', nameAr: 'هونغ كونغ' },
  { code: 'IN', nameAr: 'الهند' },
  { code: 'PK', nameAr: 'باكستان' },
  { code: 'BD', nameAr: 'بنغلاديش' },
  { code: 'LK', nameAr: 'سريلانكا' },
  { code: 'NP', nameAr: 'نيبال' },
  { code: 'BT', nameAr: 'بوتان' },
  { code: 'MV', nameAr: 'جزر المالديف' },
  { code: 'AF', nameAr: 'أفغانستان' },
  { code: 'IR', nameAr: 'إيران' },
  { code: 'TR', nameAr: 'تركيا' },
  { code: 'CY', nameAr: 'قبرص' },
  { code: 'IL', nameAr: 'إسرائيل' },
  { code: 'KZ', nameAr: 'كازاخستان' },
  { code: 'UZ', nameAr: 'أوزبكستان' },
  { code: 'TM', nameAr: 'تركمانستان' },
  { code: 'TJ', nameAr: 'طاجيكستان' },
  { code: 'KG', nameAr: 'قرغستان' },
  { code: 'AZ', nameAr: 'أذربيجان' },
  { code: 'AM', nameAr: 'أرمينيا' },
  { code: 'GE', nameAr: 'جورجيا' },
  { code: 'RU', nameAr: 'روسيا' },
  { code: 'UA', nameAr: 'أوكرانيا' },
  { code: 'BY', nameAr: 'بيلاروسيا' },
  { code: 'MD', nameAr: 'مولدوفا' },
  { code: 'PL', nameAr: 'بولندا' },
  { code: 'CZ', nameAr: 'التشيك' },
  { code: 'SK', nameAr: 'سلوفاكيا' },
  { code: 'HU', nameAr: 'المجر' },
  { code: 'RO', nameAr: 'رومانيا' },
  { code: 'BG', nameAr: 'بلغاريا' },
  { code: 'RS', nameAr: 'صربيا' },
  { code: 'HR', nameAr: 'كرواتيا' },
  { code: 'SI', nameAr: 'سلوفينيا' },
  { code: 'BA', nameAr: 'البوسنة والهرسك' },
  { code: 'ME', nameAr: 'الجبل الأسود' },
  { code: 'MK', nameAr: 'مقدونيا الشمالية' },
  { code: 'AL', nameAr: 'ألبانيا' },
  { code: 'XK', nameAr: 'كوسوفو' },
  { code: 'GR', nameAr: 'اليونان' },
  { code: 'IT', nameAr: 'إيطاليا' },
  { code: 'MT', nameAr: 'مالطا' },
  { code: 'ES', nameAr: 'إسبانيا' },
  { code: 'PT', nameAr: 'البرتغال' },
  { code: 'FR', nameAr: 'فرنسا' },
  { code: 'MC', nameAr: 'موناكو' },
  { code: 'AD', nameAr: 'أندورا' },
  { code: 'DE', nameAr: 'ألمانيا' },
  { code: 'AT', nameAr: 'النمسا' },
  { code: 'CH', nameAr: 'سويسرا' },
  { code: 'LI', nameAr: 'ليختنشتاين' },
  { code: 'NL', nameAr: 'هولندا' },
  { code: 'BE', nameAr: 'بلجيكا' },
  { code: 'LU', nameAr: 'لوكسمبورغ' },
  { code: 'GB', nameAr: 'المملكة المتحدة' },
  { code: 'IE', nameAr: 'أيرلندا' },
  { code: 'IS', nameAr: 'آيسلندا' },
  { code: 'DK', nameAr: 'الدنمارك' },
  { code: 'NO', nameAr: 'النرويج' },
  { code: 'SE', nameAr: 'السويد' },
  { code: 'FI', nameAr: 'فنلندا' },
  { code: 'EE', nameAr: 'إستونيا' },
  { code: 'LV', nameAr: 'لاتفيا' },
  { code: 'LT', nameAr: 'ليتوانيا' },
  { code: 'US', nameAr: 'الولايات المتحدة' },
  { code: 'CA', nameAr: 'كندا' },
  { code: 'MX', nameAr: 'المكسيك' },
  { code: 'GT', nameAr: 'غواتيمالا' },
  { code: 'BZ', nameAr: 'بليز' },
  { code: 'HN', nameAr: 'هندوراس' },
  { code: 'SV', nameAr: 'السلفادور' },
  { code: 'NI', nameAr: 'نيكاراغوا' },
  { code: 'CR', nameAr: 'كوستاريكا' },
  { code: 'PA', nameAr: 'بنما' },
  { code: 'CU', nameAr: 'كوبا' },
  { code: 'JM', nameAr: 'جامايكا' },
  { code: 'HT', nameAr: 'هايتي' },
  { code: 'DO', nameAr: 'جمهورية الدومينيكان' },
  { code: 'TT', nameAr: 'ترينيداد وتوباغو' },
  { code: 'BS', nameAr: 'باهاماس' },
  { code: 'BB', nameAr: 'بربادوس' },
  { code: 'CO', nameAr: 'كولومبيا' },
  { code: 'VE', nameAr: 'فنزويلا' },
  { code: 'GY', nameAr: 'غيانا' },
  { code: 'SR', nameAr: 'سورينام' },
  { code: 'EC', nameAr: 'الإكوادور' },
  { code: 'PE', nameAr: 'بيرو' },
  { code: 'BR', nameAr: 'البرازيل' },
  { code: 'BO', nameAr: 'بوليفيا' },
  { code: 'PY', nameAr: 'باراغواي' },
  { code: 'UY', nameAr: 'الأوروغواي' },
  { code: 'AR', nameAr: 'الأرجنتين' },
  { code: 'CL', nameAr: 'تشيلي' },
  { code: 'NG', nameAr: 'نيجيريا' },
  { code: 'NE', nameAr: 'النيجر' },
  { code: 'TD', nameAr: 'تشاد' },
  { code: 'ML', nameAr: 'مالي' },
  { code: 'BF', nameAr: 'بوركينا فاسو' },
  { code: 'SN', nameAr: 'السنغال' },
  { code: 'GM', nameAr: 'غامبيا' },
  { code: 'GW', nameAr: 'غينيا بيساو' },
  { code: 'GN', nameAr: 'غينيا' },
  { code: 'SL', nameAr: 'سيراليون' },
  { code: 'LR', nameAr: 'ليبيريا' },
  { code: 'CI', nameAr: 'ساحل العاج' },
  { code: 'GH', nameAr: 'غانا' },
  { code: 'TG', nameAr: 'توغو' },
  { code: 'BJ', nameAr: 'بنين' },
  { code: 'CM', nameAr: 'الكاميرون' },
  { code: 'CF', nameAr: 'أفريقيا الوسطى' },
  { code: 'GQ', nameAr: 'غينيا الاستوائية' },
  { code: 'GA', nameAr: 'الغابون' },
  { code: 'CG', nameAr: 'كونغو' },
  { code: 'CD', nameAr: 'جمهورية الكونغو الديمقراطية' },
  { code: 'ST', nameAr: 'ساو تومي وبرينسيبي' },
  { code: 'CV', nameAr: 'الرأس الأخضر' },
  { code: 'AO', nameAr: 'أنغولا' },
  { code: 'ZM', nameAr: 'زامبيا' },
  { code: 'MW', nameAr: 'مالاوي' },
  { code: 'MZ', nameAr: 'موزمبيق' },
  { code: 'ZW', nameAr: 'زيمبابوي' },
  { code: 'BW', nameAr: 'بوتسوانا' },
  { code: 'NA', nameAr: 'ناميبيا' },
  { code: 'ZA', nameAr: 'جنوب أفريقيا' },
  { code: 'SZ', nameAr: 'إسواتيني' },
  { code: 'LS', nameAr: 'ليسوتو' },
  { code: 'ET', nameAr: 'إثيوبيا' },
  { code: 'ER', nameAr: 'إريتريا' },
  { code: 'SS', nameAr: 'جنوب السودان' },
  { code: 'UG', nameAr: 'أوغندا' },
  { code: 'KE', nameAr: 'كينيا' },
  { code: 'TZ', nameAr: 'تنزانيا' },
  { code: 'RW', nameAr: 'رواندا' },
  { code: 'BI', nameAr: 'بوروندي' },
  { code: 'MG', nameAr: 'مدغشقر' },
  { code: 'MU', nameAr: 'موريشيوس' },
  { code: 'SC', nameAr: 'سيشل' },
  { code: 'AU', nameAr: 'أستراليا' },
  { code: 'NZ', nameAr: 'نيوزيلندا' },
  { code: 'PG', nameAr: 'بابوا غينيا الجديدة' },
  { code: 'FJ', nameAr: 'فيجي' },
  { code: 'SB', nameAr: 'جزر سليمان' },
  { code: 'VU', nameAr: 'فانواتو' },
  { code: 'WS', nameAr: 'ساموا' },
  { code: 'TO', nameAr: 'تونغا' },
  { code: 'KI', nameAr: 'كيريباتي' },
  { code: 'FM', nameAr: 'ميكرونيزيا' },
  { code: 'MH', nameAr: 'جزر مارشال' },
  { code: 'PW', nameAr: 'بالاو' },
  { code: 'NR', nameAr: 'ناورو' },
  { code: 'TV', nameAr: 'توفالو' },
];

export const COUNTRY_NAME_BY_CODE: Record<string, string> = Object.fromEntries(
  COUNTRIES.map((c) => [c.code, c.nameAr])
);

export function countryNameFor(code: string | null): string {
  if (!code) return '—';
  return COUNTRY_NAME_BY_CODE[code] ?? code;
}
