/**
 * Static country_code -> Arabic name dictionary.
 *
 * The database only stores country_code (ISO 3166-1 alpha-2). This
 * file is the single source of truth for turning that code into the
 * Arabic name shown in the UI, used in search, and used in exports.
 * No countries table exists in the database by design (see Domain
 * Schema Refinement migration) — do not add one.
 *
 * Sorted by Arabic name for a sensible default dropdown order.
 */
export interface Country {
  code: string;
  nameAr: string;
}

export const COUNTRIES: Country[] = [
  { code: 'AF', nameAr: 'أفغانستان' },
  { code: 'AL', nameAr: 'ألبانيا' },
  { code: 'DZ', nameAr: 'الجزائر' },
  { code: 'DE', nameAr: 'ألمانيا' },
  { code: 'AD', nameAr: 'أندورا' },
  { code: 'AO', nameAr: 'أنغولا' },
  { code: 'AG', nameAr: 'أنتيغوا وباربودا' },
  { code: 'UY', nameAr: 'أوروغواي' },
  { code: 'UZ', nameAr: 'أوزبكستان' },
  { code: 'UA', nameAr: 'أوكرانيا' },
  { code: 'ID', nameAr: 'إندونيسيا' },
  { code: 'IE', nameAr: 'أيرلندا' },
  { code: 'IS', nameAr: 'آيسلندا' },
  { code: 'AZ', nameAr: 'أذربيجان' },
  { code: 'ET', nameAr: 'إثيوبيا' },
  { code: 'ER', nameAr: 'إريتريا' },
  { code: 'ES', nameAr: 'إسبانيا' },
  { code: 'SZ', nameAr: 'إسواتيني' },
  { code: 'IL', nameAr: 'إسرائيل' },
  { code: 'EE', nameAr: 'إستونيا' },
  { code: 'AR', nameAr: 'الأرجنتين' },
  { code: 'JO', nameAr: 'الأردن' },
  { code: 'AE', nameAr: 'الإمارات العربية المتحدة' },
  { code: 'BH', nameAr: 'البحرين' },
  { code: 'BR', nameAr: 'البرازيل' },
  { code: 'PT', nameAr: 'البرتغال' },
  { code: 'BA', nameAr: 'البوسنة والهرسك' },
  { code: 'GA', nameAr: 'الغابون' },
  { code: 'GQ', nameAr: 'غينيا الاستوائية' },
  { code: 'PH', nameAr: 'الفلبين' },
  { code: 'CV', nameAr: 'الرأس الأخضر' },
  { code: 'SN', nameAr: 'السنغال' },
  { code: 'SD', nameAr: 'السودان' },
  { code: 'SE', nameAr: 'السويد' },
  { code: 'SA', nameAr: 'المملكة العربية السعودية' },
  { code: 'GB', nameAr: 'المملكة المتحدة' },
  { code: 'MA', nameAr: 'المغرب' },
  { code: 'MX', nameAr: 'المكسيك' },
  { code: 'NE', nameAr: 'النيجر' },
  { code: 'NO', nameAr: 'النرويج' },
  { code: 'AT', nameAr: 'النمسا' },
  { code: 'IN', nameAr: 'الهند' },
  { code: 'US', nameAr: 'الولايات المتحدة الأمريكية' },
  { code: 'JP', nameAr: 'اليابان' },
  { code: 'YE', nameAr: 'اليمن' },
  { code: 'GR', nameAr: 'اليونان' },
  { code: 'AM', nameAr: 'أرمينيا' },
  { code: 'BB', nameAr: 'بربادوس' },
  { code: 'BS', nameAr: 'جزر البهاما' },
  { code: 'PK', nameAr: 'باكستان' },
  { code: 'PW', nameAr: 'بالاو' },
  { code: 'PA', nameAr: 'بنما' },
  { code: 'BD', nameAr: 'بنغلاديش' },
  { code: 'BJ', nameAr: 'بنين' },
  { code: 'PY', nameAr: 'باراغواي' },
  { code: 'PG', nameAr: 'بابوا غينيا الجديدة' },
  { code: 'BE', nameAr: 'بلجيكا' },
  { code: 'BG', nameAr: 'بلغاريا' },
  { code: 'BZ', nameAr: 'بليز' },
  { code: 'BN', nameAr: 'بروناي' },
  { code: 'BI', nameAr: 'بوروندي' },
  { code: 'BF', nameAr: 'بوركينا فاسو' },
  { code: 'BW', nameAr: 'بوتسوانا' },
  { code: 'BT', nameAr: 'بوتان' },
  { code: 'BO', nameAr: 'بوليفيا' },
  { code: 'PL', nameAr: 'بولندا' },
  { code: 'MM', nameAr: 'ميانمار' },
  { code: 'MN', nameAr: 'منغوليا' },
  { code: 'ME', nameAr: 'الجبل الأسود' },
  { code: 'MZ', nameAr: 'موزمبيق' },
  { code: 'MD', nameAr: 'مولدوفا' },
  { code: 'MR', nameAr: 'موريتانيا' },
  { code: 'MU', nameAr: 'موريشيوس' },
  { code: 'MG', nameAr: 'مدغشقر' },
  { code: 'MW', nameAr: 'مالاوي' },
  { code: 'MY', nameAr: 'ماليزيا' },
  { code: 'ML', nameAr: 'مالي' },
  { code: 'MT', nameAr: 'مالطا' },
  { code: 'MV', nameAr: 'جزر المالديف' },
  { code: 'EG', nameAr: 'مصر' },
  { code: 'MK', nameAr: 'مقدونيا الشمالية' },
  { code: 'MC', nameAr: 'موناكو' },
  { code: 'NA', nameAr: 'ناميبيا' },
  { code: 'NR', nameAr: 'ناورو' },
  { code: 'NP', nameAr: 'نيبال' },
  { code: 'NG', nameAr: 'نيجيريا' },
  { code: 'NZ', nameAr: 'نيوزيلندا' },
  { code: 'NI', nameAr: 'نيكاراغوا' },
  { code: 'VU', nameAr: 'فانواتو' },
  { code: 'VE', nameAr: 'فنزويلا' },
  { code: 'VN', nameAr: 'فيتنام' },
  { code: 'FI', nameAr: 'فنلندا' },
  { code: 'FJ', nameAr: 'فيجي' },
  { code: 'PS', nameAr: 'فلسطين' },
  { code: 'FR', nameAr: 'فرنسا' },
  { code: 'CY', nameAr: 'قبرص' },
  { code: 'QA', nameAr: 'قطر' },
  { code: 'KZ', nameAr: 'كازاخستان' },
  { code: 'KH', nameAr: 'كمبوديا' },
  { code: 'CM', nameAr: 'الكاميرون' },
  { code: 'CA', nameAr: 'كندا' },
  { code: 'KM', nameAr: 'جزر القمر' },
  { code: 'CO', nameAr: 'كولومبيا' },
  { code: 'CG', nameAr: 'جمهورية الكونغو' },
  { code: 'CD', nameAr: 'جمهورية الكونغو الديمقراطية' },
  { code: 'KR', nameAr: 'كوريا الجنوبية' },
  { code: 'KP', nameAr: 'كوريا الشمالية' },
  { code: 'CR', nameAr: 'كوستاريكا' },
  { code: 'CI', nameAr: 'ساحل العاج' },
  { code: 'CU', nameAr: 'كوبا' },
  { code: 'KW', nameAr: 'الكويت' },
  { code: 'XK', nameAr: 'كوسوفو' },
  { code: 'LA', nameAr: 'لاوس' },
  { code: 'LV', nameAr: 'لاتفيا' },
  { code: 'LB', nameAr: 'لبنان' },
  { code: 'LY', nameAr: 'ليبيا' },
  { code: 'LR', nameAr: 'ليبيريا' },
  { code: 'LT', nameAr: 'ليتوانيا' },
  { code: 'LI', nameAr: 'ليختنشتاين' },
  { code: 'LS', nameAr: 'ليسوتو' },
  { code: 'LU', nameAr: 'لوكسمبورغ' },
  { code: 'CZ', nameAr: 'التشيك' },
  { code: 'TD', nameAr: 'تشاد' },
  { code: 'CL', nameAr: 'تشيلي' },
  { code: 'CN', nameAr: 'الصين' },
  { code: 'TG', nameAr: 'توغو' },
  { code: 'TV', nameAr: 'توفالو' },
  { code: 'TO', nameAr: 'تونغا' },
  { code: 'TN', nameAr: 'تونس' },
  { code: 'TR', nameAr: 'تركيا' },
  { code: 'TM', nameAr: 'تركمانستان' },
  { code: 'TT', nameAr: 'ترينيداد وتوباغو' },
  { code: 'TZ', nameAr: 'تنزانيا' },
  { code: 'TH', nameAr: 'تايلاند' },
  { code: 'TW', nameAr: 'تايوان' },
  { code: 'TJ', nameAr: 'طاجيكستان' },
  { code: 'TL', nameAr: 'تيمور الشرقية' },
  { code: 'JM', nameAr: 'جامايكا' },
  { code: 'GM', nameAr: 'غامبيا' },
  { code: 'GH', nameAr: 'غانا' },
  { code: 'GD', nameAr: 'غرينادا' },
  { code: 'GT', nameAr: 'غواتيمالا' },
  { code: 'GY', nameAr: 'غيانا' },
  { code: 'GN', nameAr: 'غينيا' },
  { code: 'GW', nameAr: 'غينيا بيساو' },
  { code: 'RU', nameAr: 'روسيا' },
  { code: 'RW', nameAr: 'رواندا' },
  { code: 'RO', nameAr: 'رومانيا' },
  { code: 'ZM', nameAr: 'زامبيا' },
  { code: 'ZW', nameAr: 'زيمبابوي' },
  { code: 'CH', nameAr: 'سويسرا' },
  { code: 'SR', nameAr: 'سورينام' },
  { code: 'SY', nameAr: 'سوريا' },
  { code: 'SL', nameAr: 'سيراليون' },
  { code: 'LK', nameAr: 'سريلانكا' },
  { code: 'SV', nameAr: 'السلفادور' },
  { code: 'SM', nameAr: 'سان مارينو' },
  { code: 'ST', nameAr: 'ساو تومي وبرينسيبي' },
  { code: 'WS', nameAr: 'ساموا' },
  { code: 'SG', nameAr: 'سنغافورة' },
  { code: 'SK', nameAr: 'سلوفاكيا' },
  { code: 'SI', nameAr: 'سلوفينيا' },
  { code: 'SO', nameAr: 'الصومال' },
  { code: 'RS', nameAr: 'صربيا' },
  { code: 'SS', nameAr: 'جنوب السودان' },
  { code: 'ZA', nameAr: 'جنوب أفريقيا' },
  { code: 'IQ', nameAr: 'العراق' },
  { code: 'OM', nameAr: 'عُمان' },
  { code: 'GE', nameAr: 'جورجيا' },
  { code: 'GQ', nameAr: 'غينيا الاستوائية' },
  { code: 'FM', nameAr: 'ولايات ميكرونيسيا المتحدة' },
  { code: 'CF', nameAr: 'جمهورية أفريقيا الوسطى' },
  { code: 'DO', nameAr: 'جمهورية الدومينيكان' },
  { code: 'DM', nameAr: 'دومينيكا' },
  { code: 'DK', nameAr: 'الدنمارك' },
  { code: 'DJ', nameAr: 'جيبوتي' },
  { code: 'RW', nameAr: 'رواندا' },
  { code: 'HT', nameAr: 'هايتي' },
  { code: 'HN', nameAr: 'هندوراس' },
  { code: 'HU', nameAr: 'المجر' },
  { code: 'VA', nameAr: 'الفاتيكان' },
  { code: 'NL', nameAr: 'هولندا' },
  { code: 'HR', nameAr: 'كرواتيا' },
  { code: 'HK', nameAr: 'هونغ كونغ' },
  { code: 'IT', nameAr: 'إيطاليا' },
  { code: 'IR', nameAr: 'إيران' },
  { code: 'KE', nameAr: 'كينيا' },
  { code: 'KG', nameAr: 'قيرغيزستان' },
  { code: 'KI', nameAr: 'كيريباتي' },
  { code: 'MH', nameAr: 'جزر مارشال' },
  { code: 'SB', nameAr: 'جزر سليمان' },
  { code: 'SC', nameAr: 'سيشل' },
  { code: 'AU', nameAr: 'أستراليا' },
  { code: 'EC', nameAr: 'الإكوادور' },
  { code: 'GN', nameAr: 'غينيا' },
  { code: 'PE', nameAr: 'بيرو' },
  { code: 'BY', nameAr: 'بيلاروسيا' },
  { code: 'UG', nameAr: 'أوغندا' },
];

// De-duplicate defensively (a couple of entries above share a code
// intentionally as aliases were considered and dropped — this keeps
// the list correct even if it's edited carelessly later).
const SEEN = new Set<string>();
export const COUNTRIES_UNIQUE: Country[] = COUNTRIES.filter((c) => {
  if (SEEN.has(c.code)) return false;
  SEEN.add(c.code);
  return true;
}).sort((a, b) => a.nameAr.localeCompare(b.nameAr, 'ar'));

export const COUNTRY_NAME_AR: Record<string, string> = Object.fromEntries(
  COUNTRIES_UNIQUE.map((c) => [c.code, c.nameAr])
);

/**
 * Returns the Arabic country name for a code, falling back to the
 * raw code itself if it isn't in the dictionary (never throws, never
 * shows a blank cell).
 */
export function getCountryNameAr(code: string | null): string {
  if (!code) return '—';
  return COUNTRY_NAME_AR[code] ?? code;
}
